### ISSUE TITLE
Transposed/repeated weights in first notebook

### ISSUE THREAD

**Issue by masonproffitt** [arokem/conv-nets#1]
In 001-neural-nets.ipynb, some of the weights in cells 9 and 13 are drawn on the wrong lines. Specifically, w^2_{12} and w^2_{21} are transposed. Looking in utils.py, it looks like they are associated with the right lines, but they just get drawn in confusing spots.

Also, in cells 11, 17, and 22, w_2_21 shows up in the calculation of two different nodes in the second layer. It should be w_2_21 for the first node and w_2_12 for the second node.

**Comment by arokem** [comment]
Thanks for reporting. Will fix this in a couple of weeks, when I prepare this for the next time I am presenting this!
